services:
  web:
    image: adduc/nginx-alpine:${ALPINE_VERSION}-amd64
    ports: ["80:80"]
    # define cpu limit to 1000m
    cpus: 2
    mem_limit: 128m
    environment:
      VHOST_PHP_DEFAULT: _ /srv/public app:9000
    volumes:
      - ./example:/srv

  app:
    image: adduc/php-alpine:${PHP_VERSION}-work-${ALPINE_VERSION}-amd64
    environment:
      FPM_POOL_DEFAULT: 0:9000 5
    volumes:
      - ./example:/srv

  db:
    image: mariadb:11.4
