---
services:
  server:
    image: rancher/k3s:v1.32.1-k3s1
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data/k3s-server:/var/lib/rancher/k3s
      - .:/output
    ports:
      - 6443:6443  # Kubernetes API Server
    entrypoint: sh -c "\
      mount --make-shared / \
      && k3s server \
        --cluster-init \
        --disable=traefik \
        --disable=servicelb \
        --node-name=example \
        --etcd-expose-metrics \
        --kube-controller-manager-arg bind-address=0.0.0.0 \
        --kube-proxy-arg metrics-bind-address=0.0.0.0 \
        --kube-scheduler-arg bind-address=0.0.0.0 \
      "
    environment:
      - K3S_TOKEN=example
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
