---
services:
  pg15:
    image: postgres:15-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  pgupgrade:
    image: pgautoupgrade/pgautoupgrade:16-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  pg16:
    image: postgres:16-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
