---
services:
  server:
    image: rancher/k3s:v1.33.4-k3s1
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data/k3s-server:/var/lib/rancher/k3s
      - ./data/persistent-volumes:/opt/local-path-provisioner
      - .:/output
    ports:
      - 6443:6443  # Kubernetes API Server
    command:
      - server
      - --disable=metrics-server
      - --disable=traefik
      - --disable=servicelb
      - --disable=local-storage
      - --node-name=example
    environment:
      - K3S_TOKEN=example
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
