---
services:
  server:
    image: rancher/k3s:v1.32.1-k3s1
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data/k3s-server:/var/lib/rancher/k3s
      - ./data/persistent-volumes:/opt/local-path-provisioner
      - .:/output
    ports:
      - 6443:6443    # Kubernetes API Server
      - 30080:30080  # HTTP NodePort
      - 30443:30443  # HTTPS NodePort
    command:
      - server
      - --disable=metrics-server
      - --disable=traefik
      - --disable=servicelb
      - --node-name=example
    environment:
      - K3S_TOKEN=example
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    healthcheck:
      test: ["CMD", "kubectl", "get", "--raw=/readyz"]
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 10
