services:
  web:
    image: local/nginx-alpine:3.22-amd64
    ports: ["80:80"]
    cpus: 1
    mem_limit: 128m
    environment:
      VHOST_PHP_DEFAULT: _ /srv app:9000
      FILE_EXAMPLE_DEFAULT: /srv/index.php

  app:
    image: local/php-alpine:84-local-3.22-amd64
    environment:
      FPM_POOL_DEFAULT: 0:9000 3
    volumes:
      - ./:/srv
