---
- name: Example Playbook
  hosts: target
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        install_recommends: false
        cache_valid_time: 86400
        update_cache: true

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true
