---
# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build all variants
    cmds:
      - echo "Building all variants..."

  build-arch-*:
    desc: Build all variants for a specific architecture
    cmds:
      - echo 'Building all variants for architecture {{index .MATCH 0}}'

  build-version-*:
    desc: Build all variants for a specific version
    cmds:
      - echo 'Building all variants for version {{index .MATCH 0}}'
