---
services:
  server:
    build: server
    working_dir: /etc/ansible
    volumes:
      - ./ansible:/etc/ansible

      # Mount the user's SSH keys to use when running Ansible playbooks.
      - ~/.ssh:/mnt/user-ssh:ro

      # Mount the system's SSH configuration to trust the SSH keys
      # and allow Ansible to connect to the target container without
      # prompting to accept the host key.
      - /etc/ssh:/mnt/system-ssh:ro

    # Handling trap signals gives the opportunity for graceful shutdown,
    # and has the side effect of generally being faster than letting
    # docker stop time out and kill the container.
    init: true

    # Keep the container running by providing a command that does not
    # exit.
    command: sleep infinity


  target:
    build: target

    # To replicate a typical Ubuntu server environment, we will use
    # systemd as the init system. Unlike other init systems, systemd
    # requires a few additional configurations to work properly in
    # a container.
    cgroup: host
    tmpfs: [/run]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

      # If SSH keys are mounted, the entry point script will
      # automatically trust them to allow Ansible to connect
      # to the target container.
      - ~/.ssh:/mnt/user-ssh:ro

      # Mount the system's SSH configuration to use the SSH keys instead
      # of generating new ones each time the container starts.
      - /etc/ssh:/mnt/system-ssh:ro

    # This is optional, but it allows you to see the output of systemd
    # in the container logs, which can be useful for debugging.
    tty: true
