---
services:
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    image: php:8.4-fpm-alpine
    volumes:
      - ./:/var/www/html
