---
# yamllint disable rule:line-length
##
# Dynamic configuration for Traefik
#
# @see https://doc.traefik.io/traefik/reference/install-configuration/providers/others/file/
##
# yamllint enable

http:
  routers:
    example-router:
      entrypoints: ["web"]
      rule: "HostRegexp(`example\\..*`)"
      service: example-service

  services:
    example-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://example.com"
