---
# yamllint disable rule:line-length
##
# Traefik Static Configuration
#
# @see https://doc.traefik.io/traefik/reference/install-configuration/boot-environment/#file
##
# yamllint enable

# API Configuration

api:
  insecure: true

# EntryPoints Configuration

entryPoints:
  web:
    address: :80

# Providers Configuration

providers:
  file:
    filename: /dynamic.yml
    watch: true
