---
services:
  ollama:
    image: ollama/ollama:${IMAGE_TAG:?use latest if nvidia, rocm if amd}
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ./data:/root/.ollama
    ports:
      - "11434:11434"
