---
name: "Terraform:Style"

'on':
  workflow_call:
    inputs:
      terraform_version:
        description: "Terraform version"
        required: false
        type: string
        default: "1.11.3"
      tflint_version:
        description: "TFLint version"
        required: false
        type: string
        default: "v0.52.0"
      module_dirs:
        description: "Terraform module directories (JSON array)"
        required: true
        type: string

jobs:
  style:
    name: Style
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.11.3"

      - name: Setup TFLint
        # yamllint disable rule:line-length
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6
        # yamllint enable
        with:
          tflint_version: "v0.52.0"

      - name: Format Terraform
        run: |
          set -o pipefail -o errexit -o nounset

          DIRS_JSON='${{ inputs.module_dirs }}'
          DIRS=$(echo $DIRS_JSON | jq -r '.[]')

          DIFF=$(terraform fmt -diff -recursive $DIRS 2>&1)
          if [ -n "$DIFF" ]; then
            echo "At least one Terraform file is not formatted correctly:"
            echo "$DIFF"
            exit 1
          else
            echo "All Terraform files are formatted correctly."
          fi

      - name: Validate Terraform
        run: |
          set -o pipefail -o errexit -o nounset -o xtrace

          DIRS_JSON='${{ inputs.module_dirs }}'
          DIRS=$(echo $DIRS_JSON | jq -r '.[]')

          for dir in $DIRS; do
            tflint --chdir $dir
          done
