name: PR:Golang

on:
  pull_request:
    paths:
      # This workflow
      - '.github/workflows/pr-bash.yml'
      # Shell scripts
      - '**.sh'

permissions:
  contents: read # used by actions/checkout

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck Analysis
        uses: reactive-firewall/shellcheck-scan@v1