---
name: PR:Bash

'on':
  pull_request:
    paths:
      # This workflow
      - '.github/workflows/pr-bash.yml'
      # Shell scripts
      - '**/*.sh'

permissions:
  contents: read  # used by actions/checkout

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          version: v0.10.0

      - name: Lint (ShellCheck)
        run: find . -name '*.sh' -execdir shellcheck {} \;
