---
services:
  web:
    image: local/nginx-alpine:${ALPINE_VERSION}-amd64
    ports: ["80:80"]
    # the image determines worker processes based on the number of CPUs
    cpus: 2
    mem_limit: 128m
    environment:
      # The image will transform this into a vhost config file
      # VHOST_PHP_<NAME>: <HOSTNAME> <DOCUMENT_ROOT> <PHP-FPM-SOCKET>
      VHOST_PHP_DEFAULT: _ /srv/public app:9000
    volumes:
      - ./example:/srv

  app:
    image: local/php-alpine:${PHP_VERSION}-work-${ALPINE_VERSION}-amd64
    environment:
      # The image will transform this into a PHP-FPM pool config file
      # FPM_POOL_<NAME>: <LISTEN> <PM_MAX_CHILDREN>
      FPM_POOL_DEFAULT: 0:9000 5
      DEFAULT_FPM_POOL_UID: ${UID}
    volumes:
      - ./example:/srv
